apiVersion: v1
kind: Service
metadata:
  name: journal-api-service
  labels:                  # <--- Add this section!
    app: journal-api 
spec:
  # This creates a real AWS Load Balancer (ELB)
  type: LoadBalancer 
  
  # The 'selector' is the magic glue: 
  # It finds all Pods with the label 'app: journal-api' and sends traffic to them.
  selector:
    app: journal-api
    
  ports:
  - protocol: TCP
    port: 80          # The port exposed to the internet (standard HTTP port)
    targetPort: 8000  # The port your FastAPI app is listening on (inside the container)
    name: http 
